### ISSUE TITLE
mender-client connection issue

### ISSUE THREAD

**Issue by NTohan** [mendersoftware/mender-server#112]
With main branch on hash 7dfc4d8501f58142cb0d45595ea3d0163908efa6 mender-client is not able to connect to the mender-server deployed in the production mode. 

mender-client connection is tested on the target device using a local IP with mender-server running on the same network

```
$ wget -O- https://get.mender.io/ | sudo bash -s -- --demo --force-mender-client4 -- --quiet --device-type "genericx86-64" --demo --server-url https://192.168.x.x/ --server-cert=""
```
Using above command leads to no connection and no new device pending for approval on mender-server running in the same network. 

**Workaround: Using Mender Server with Cloudflare Reverse Proxy** 
mender-client is able to connect mender-server by disabling https scheme and websecure.

``` bash
$ git diff
diff --git a/docker-compose.yml b/docker-compose.yml
index b363769..e597262 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -330,13 +330,13 @@ services:
       - --api.insecure=true
       - --accesslog=true
       - --entrypoints.web.address=:80
-      - --entrypoints.web.http.redirections.entryPoint.scheme=https
+      - --entrypoints.web.http.redirections.entryPoint.scheme=http
       - --entrypoints.web.http.redirections.entryPoint.to=websecure
       - --entrypoints.websecure.address=:443
       - --entrypoints.websecure.transport.respondingTimeouts.idleTimeout=7200
       - --entrypoints.websecure.transport.respondingTimeouts.readTimeout=7200
       - --entrypoints.websecure.transport.respondingTimeouts.writeTimeout=7200
-      - --entrypoints.websecure.http.tls=true
+      - --entrypoints.websecure.http.tls=false
       - --providers.file.directory=/etc/traefik/config
```

With https scheme and websecure.https.tls being disabled in mender-server config, we are relying on the security layer of a CDN service (cloudflare) using secure cloudflare tunnel (Cloudflare reverse proxy). This setup allows us to access mender-server using **https**://devices.domain.xxx  pointing to http://192.168.x.x:**443** and install mender-client on the target device using:

```
$ wget -O- https://get.mender.io/ | sudo bash -s -- --demo --force-mender-client4 -- --quiet --device-type "genericx86-64" --demo --server-url https://devices.domain.xxx/ --server-cert=""
```

Is this a recommend workflow to use mender-server or will you recommend to rely on mender-server https and webecure due to security concerns? 

Thank you in advance for any inputs. 

Cheers, N.T.

**Comment by alfrunes** [comment]
Hello,
Thanks again for feedback. The Docker Compose setup is only meant for demo / evaluation purposes only and should not be used for production environments. When going to production I highly suggest using Kubernetes with our helm chart https://github.com/mendersoftware/mender-helm.

If you still want to use the docker compose setup, https://github.com/mendersoftware/mender-server/pull/110 introduces a (self-signed) demo certificate. You can use that as a basis and issue your own public certificate and mount it (for example by replacing the `compose/certs/mender.crt` and `compose/certs/mender.key` with your certificate and key respectively).

**Comment by alfrunes** [comment]
Another option, if you want to use compose behind a reverse proxy handling the TLS termination. You can simply disable the `websecure` entrypoint and the redirection as follows:
```
diff --git a/docker-compose.yml b/docker-compose.yml
index b363769..e597262 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -330,13 +330,13 @@ services:
       - --api.insecure=true
       - --accesslog=true
       - --entrypoints.web.address=:80
-      - --entrypoints.web.http.redirections.entryPoint.scheme=https
-      - --entrypoints.web.http.redirections.entryPoint.to=websecure
-      - --entrypoints.websecure.address=:443
-      - --entrypoints.websecure.transport.respondingTimeouts.idleTimeout=7200
-      - --entrypoints.websecure.transport.respondingTimeouts.readTimeout=7200
-      - --entrypoints.websecure.transport.respondingTimeouts.writeTimeout=7200
-      - --entrypoints.websecure.http.tls=true
```
This way, the mender-server is exposed in plain HTTP (no TLS) on port 80.

**Comment by NTohan** [comment]
Thank you for your quick response and suggestions. I came across the helm suggestion earlier too, but simply due to limited resources on my server, I went with `docker compose`. Nevertheless, if you are suggesting that `docker compose` is/will not be maintained actively like helm, I would seriously consider upgrading my server. 

Unfortunately, your suggestion with exposing to plain HTTP did not work for me, I keep getting `404 page not found` with http://192.168.x.x:80

```
diff --git a/docker-compose.yml b/docker-compose.yml
index b363769..c9fdd05 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -330,13 +330,13 @@ services:
       - --api.insecure=true
       - --accesslog=true
       - --entrypoints.web.address=:80
-      - --entrypoints.web.http.redirections.entryPoint.scheme=https
-      - --entrypoints.web.http.redirections.entryPoint.to=websecure
-      - --entrypoints.websecure.address=:443
-      - --entrypoints.websecure.transport.respondingTimeouts.idleTimeout=7200
-      - --entrypoints.websecure.transport.respondingTimeouts.readTimeout=7200
-      - --entrypoints.websecure.transport.respondingTimeouts.writeTimeout=7200
-      - --entrypoints.websecure.http.tls=true
+        #- --entrypoints.web.http.redirections.entryPoint.scheme=https
+        #- --entrypoints.web.http.redirections.entryPoint.to=websecure
+        #- --entrypoints.websecure.address=:443
+        #- --entrypoints.websecure.transport.respondingTimeouts.idleTimeout=7200
+        #- --entrypoints.websecure.transport.respondingTimeouts.readTimeout=7200
+        #- --entrypoints.websecure.transport.respondingTimeouts.writeTimeout=7200
+        #- --entrypoints.websecure.http.tls=true
       - --providers.file.directory=/etc/traefik/config
       - --providers.docker=true
       - --providers.docker.exposedByDefault=false
```

Also, I will try generating certificates for extra layer of security but behind reverse proxy it is more or less redundant.

**Comment by alfrunes** [comment]
Sorry I was too quick to apply, not actually testing my suggestion. I identified the problem and addressed it in the PR (https://github.com/mendersoftware/mender-server/pull/110/commits/cf0b9b2175e9cf99c320e623b897f0c6a57137ca). If you now try to remove the `websecure` entrypoint from Traefik (as I described in my previous comment) it will serve plain HTTP on port 80.

> I came across the helm suggestion earlier too, but simply due to limited resources on my server, I went with docker compose. Nevertheless, if you are suggesting that docker compose is/will not be maintained actively like helm, I would seriously consider upgrading my server.

As long as it's not for a production environment. For small deployments you should be fine using this docker compose, but you might run into trouble if you need to scale the number of replicas, or load balance the application across machines. We will continue to use and improve the docker compose environment as we are also using it internally when doing system integration testing.

> Also, I will try generating certificates for extra layer of security but behind reverse proxy it is more or less redundant.

As long as your ingress (proxy) is using TLS and the docker composition is not exposed outside your secure LAN you should be ok, but be aware that port 80 will be exposed to your local network.

**Comment by NTohan** [comment]
Thank you for your fix. I am happy to confirm that with your changes and removing the `websecure` entrypoint I am able to connect to port 80. It is possible to configure the default port from 80 to something else?

The only changes I have noticed that inventory information under a registered device is empty now. Also, column configuration options under table configuration are reduced to very limited. Could this be related to the recent changes? Not a blocker for me though. 

Yes, you are right about the scaling and load balancing features K8s has to offer. I will definitely consider it for scaling. 

Regarding TLS, it is enabled by default for reverse proxy in-use.

**Comment by NTohan** [comment]
> Thank you for your fix. I am happy to confirm that with your changes and removing the `websecure` entrypoint I am able to connect to port 80. It is possible to configure the default port from 80 to something else?

Unfortunately, the deployments are constantly failing with `docker compose`  at https://github.com/mendersoftware/mender-server/commit/cf0b9b2175e9cf99c320e623b897f0c6a57137ca  and removing the websecure entrypoint
```
2024-10-19 20:58:30.714 +0000 UTC warning: Host not found (non-authoritative), try again later: GET https://s3.mender.local/mender/1392ab9b-95f7-43f4-b3f6-a12ed1f94ad2?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=mender%2F20241019%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241019T205829Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22hello-world-container-update.mender%22&response-content-type=application%2Fvnd.mender-artifact&x-id=GetObject&X-Amz-Signature=9d1aa76146d3063870369e64ba1c99580d292a8a5c2c5684ce0d34512a992655: 
```

Please find the complete logs in the file: 
[deployment-log-80fcbbce-5e16-4c3d-a77b-558031d77b3e-hello-world-container-update-2024-10-19T21_08_32.096Z.log](https://github.com/user-attachments/files/17447373/deployment-log-80fcbbce-5e16-4c3d-a77b-558031d77b3e-hello-world-container-update-2024-10-19T21_08_32.096Z.log)

**Additional information:**
`mender-client` is installed on the target device using:  

```
wget -O- https://get.mender.io | sudo bash -s -- --demo --force-mender-client4 -- --quiet --device-type "genericx86-64" --demo --server-url https://devices.domain.xxx --server-cert=""
```
`mender-client` is configured with the following parameters:
```
$ cat /etc/mender/mender.conf
{
    "HttpsClient": {},
    "Security": {},
    "Connectivity": {},
    "DeviceTypeFile": "/var/lib/mender/device_type",
    "UpdateControlMapExpirationTimeSeconds": 90,
    "UpdateControlMapBootExpirationTimeSeconds": 45,
    "UpdatePollIntervalSeconds": 5,
    "InventoryPollIntervalSeconds": 5,
    "RetryPollIntervalSeconds": 30,
    "Servers": [
        {
            "ServerURL": "https://devices.domain.xxx"
        }
    ]
}

$ cat /var/lib/mender/device_type
device_type=genericx86-64
```

Also, I have tried re-installing the `mender-client` on the target device and re-created the deployment but unfortunately the deployments are still failing. 

Can you please check the issue and confirm if it is an issue within the under-development `docker-compose` or have I configured the `mender-server` not correctly on my part?

Thank you for your efforts.

**Comment by alfrunes** [comment]
Sorry, I forgot about the s3 bucket configuration. At this point, I think these customization deserve a docker compose override file to make it easier to explain. I can see two options for making this work.

1. Use an s3 bucket and configure the server to use this bucket.
    ```yaml
    # docker-compose.http.yml
    # docker compose -f docker-compose.yml -f docker-compose.http.yml up -d
    services:
      traefik:
        command:
          - --api=true
          - --api.insecure=true
          - --accesslog=true
          - --entrypoints.web.address=:80
          - --providers.file.directory=/etc/traefik/config
          - --providers.docker=true
          - --providers.docker.exposedByDefault=false
      deployments:
        environment:
          DEPLOYMENTS_PRESIGN_URL_HOSTNAME: "<your gateway domain name>"
          DEPLOYMENTS_PRESIGN_SECRET: "<Generate a random base64 secret, for example: head -c 16 /dev/urandom | base64 -w 0 >"
          DEPLOYMENTS_STORAGE_BUCKET: "<BUCKET_NAME>"
          DEPLOYMENTS_AWS_URI: "<https://BUCKET_NAME.AWS_REGION.amazonaws.com>"
          DEPLOYMENTS_AWS_EXTERNAL_URI: "<https://BUCKET_NAME.AWS_REGION.amazonaws.com>"
          DEPLOYMENTS_AWS_AUTH_KEY: "${AWS_ACCESS_KEY_ID}"
          DEPLOYMENTS_AWS_AUTH_SECRET: "${AWS_SECRET_ACCESS_KEY}"
      s3fs:
        scale: 0
    ```
    Where `DEPLOYMENTS_AWS_AUTH_KEY` and `DEPLOYMENTS_AWS_AUTH_SECRET` is set to your secret access key for the s3 bucket.
3. Create a rule in the reverse proxy for forwarding to (with hostname rewrite) `s3.mender.local`

    ```yaml
    # docker compose -f docker-compose.yml -f docker-compose.http.yml up -d
    services:
      traefik:
        command:
          - --api=true
          - --api.insecure=true
          - --accesslog=true
          - --entrypoints.web.address=:80
          - --providers.file.directory=/etc/traefik/config
          - --providers.docker=true
          - --providers.docker.exposedByDefault=false
      deployments:
        environment:
          DEPLOYMENTS_PRESIGN_URL_HOSTNAME: "<your gateway domain name>"
          DEPLOYMENTS_PRESIGN_SECRET: "<Generate a random base64 secret, for example: head -c 16 /dev/urandom | base64 -w 0 >"
          DEPLOYMENTS_AWS_PROXY_URI: "https://<your domain>/mender" # Setup a rule that maps `/mender` to `s3.mender.local` with host header rewrite.
    ```
> [!IMPORTANT]
> If you go with option 2, make sure you using my latest version of the PR (https://github.com/mendersoftware/mender-server/pull/110/commits/bde5c31a7ca8e153683a207b599f6ddbb5cefd5f) and set `MENDER_SECRET_ACCESS_KEY` environment variable to a secret value as the s3 storage would be exposed with an insecure access key.


> It is possible to configure the default port from 80 to something else?

Yes, simply change the port number for the `web` service in the traefik service, for example:
```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index b363769..c9fdd05 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -330,13 +330,13 @@ services:
       - --api.insecure=true
       - --accesslog=true
-      - --entrypoints.web.address=:80
+      - --entrypoints.web.address=:8080
```
